### ISSUE TITLE
wordpress5.3.2版本安装后没效果，且不能打开settings

### ISSUE THREAD

**Issue by shadowfish07** [hustcc/canvas-nest.js#65]
打开settings时报错：
```
Canvas-nest.js Setting

Fatal error: Uncaught ArgumentCountError: Too few arguments to function do_settings_fields(), 1 passed in /www/wwwroot/wordpress/wp-content/plugins/canvas-nestjs/templates/settings.php on line 5 and exactly 2 expected in /www/wwwroot/wordpress/wp-admin/includes/template.php:1667 Stack trace: #0 /www/wwwroot/wordpress/wp-content/plugins/canvas-nestjs/templates/settings.php(5): do_settings_fields('WP_Canvas_Nest-...') #1 /www/wwwroot/wordpress/wp-content/plugins/canvas-nestjs/settings.php(261): include('/www/wwwroot/wo...') #2 /www/wwwroot/wordpress/wp-includes/class-wp-hook.php(288): WP_Canvas_Nest_Settings->plugin_settings_page('') #3 /www/wwwroot/wordpress/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #4 /www/wwwroot/wordpress/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #5 /www/wwwroot/wordpress/wp-admin/admin.php(254): do_action('settings_page_W...') #6 /www/wwwroot/wordpress/wp-admin/options-general.php(10): require_once('/www/wwwroot/wo...') #7 {main} thrown in /www/wwwroot/wordpress/wp-admin/includes/template.php on line 1667
```

**Comment by Qiaofanxing** [comment]
在wp-content/plugins/canvas-nestjs/templates目录下有一个settings.php文件，请将第五行改为<?php @do_settings_fields('WP_Canvas_Nest-group',0,0); ?>，第13行改为<?php @do_settings_fields('WP_Canvas_Nest-checkbox-group',0,0); ?>即可，这是因为高版本PHP禁止传参数量不匹配导致的，手动赋值即可，反正也用不上
